### ISSUE TITLE
Packages not published on Github

### ISSUE THREAD

**Issue by JigSawFr** [blacktirion/email-oauth2-proxy-docker#40]
Hi there,
It seems that despite of the fact it's written in README.
Packages are still not pushed to github registry.

ghcr.io/blacktirion/email-oauth2-proxy-docker doesn't exist and is not shown on repository.

Thanks

**Comment by moriahmorgan** [comment]
I apologize. I was doing some repo maintenance and somehow accidentally set the packages to private. Please try again and let me know.
