### ISSUE TITLE
Receiving error "Exception('Unable to load Google Auth SDK..."

### ISSUE THREAD

**Issue by johspa933** [blacktirion/email-oauth2-proxy-docker#42]
Currently I am using the Google / Service_account / CCG mode and decided to try the Docker image.  When using the latest image, I receive the following error, which I received outside of Docker that required additional modules:

Exception('Unable to load Google Auth SDK - please install the `requests` and `google-auth` modules: `python -m pip install requests google-auth`')

I will continue to use standard Python outside of Docker for now.  Please provide any progress on this when this is resolved.

Regards,
johspa

**Comment by moriahmorgan** [comment]
Added to the list of requirements and rebuild the docker container. please pull and try again.

**Comment by johspa933** [comment]
Pulled the latest image and still receiving the error...

emailproxy  | 2024-01-24 03:48:25,718: Caught exception while requesting OAuth 2.0 credentials for xxx@yyy.zzz: Exception('Unable to load Google Auth SDK - please install the `requests` and `google-auth` modules: `python -m pip install requests google-auth`')

Regards,
Johspa

**Comment by moriahmorgan** [comment]
@johspa933 my apologies, I made an assumption regarding the requests package, thinking it was rolled into another package installation as a dependency.

Both packages should be installed now.

**Comment by johspa933** [comment]
Pulled the latest image and it is working fine now.

Thank you for the quick response and apologies for the delay in providing test results.

Regards,
Johspa

**Comment by johspa933** [comment]
Pulled the latest image and it is working fine now.

Thank you for the quick response and apologies for the delay in providing test results.

Regards,
Johspa
